# Generated by Django 4.1 on 2022-09-25 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('primer_nombre', models.CharField(max_length=10)),
                ('segundo_nombre', models.CharField(max_length=10)),
                ('primer_apellido', models.CharField(max_length=10)),
                ('segundo_apellido', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=40)),
                ('correo_empleado', models.CharField(max_length=50)),
                ('direccion_empleado', models.CharField(max_length=40)),
                ('celular_empleado', models.CharField(max_length=15)),
                ('tipo_contrato', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=25)),
                ('banco', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo_empresa', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nombre_empresa', models.CharField(max_length=40)),
                ('nit', models.IntegerField()),
                ('nombre_contacto', models.CharField(max_length=40)),
                ('cargo_contacto', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=20)),
                ('correo_empresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('user_password', models.CharField(max_length=15)),
                ('tipo_rol', models.CharField(choices=[('Empleado', 'Empleado'), ('Administrador', 'Administrador')], max_length=15)),
                ('data_create', models.DateField(default=datetime.datetime.now)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcadenadealimentos.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_registro', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('valor', models.IntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('Ing', 'Ingresos'), ('Egr', 'Egreso')], max_length=3)),
                ('movimiento_fecha', models.DateField()),
                ('codigo_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcadenadealimentos.empresa')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcadenadealimentos.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcadenadealimentos.empresa'),
        ),
    ]
